web:
  build: .
  command: 'bash -c ''golang-docker-heroku'''
  working_dir: /app/user/src/github.com/aizwellenstan/golang-docker-heroku
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
shell:
  build: .
  command: bash
  working_dir: /app/user/src/github.com/aizwellenstan/golang-docker-heroku
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user/src/github.com/aizwellenstan/golang-docker-heroku'
